# -*- coding: utf-8 -*-
"""Generated by ArcGIS ModelBuilder on: 2019-12-03 14:32:22
All ModelBuilder functionality may not be exported. Edits may be required for equivalency with the original model.
"""

import arcpy
import json

# To allow overwriting the outputs change the overwrite option to true.
arcpy.env.overwriteOutput = False

# Script parameters
arcpy.env.workspace = arcpy.GetParameterAsText(0)

#Make sure to drop the config file in your ArcPro project
with open(arcpy.env.workspace+'/config.json') as json_data_file:
    data = json.load(json_data_file)

# Local variables:
roads_buffer_clip2 = data["temp_paths"]["roads_buffer_clip2"]
project_locations = data["wfs_paths"]["WFS_project_locations_path"]
project_listings = data["wfs_paths"]["WFS_project_listings_path"]

# Process: Join

try:
    arcpy.AddJoin_management(project_locations, "CCID", project_listings, "CCID")
except BaseException as e:
    pass




