# -*- coding: utf-8 -*-
"""Generated by ArcGIS ModelBuilder on: 2019-12-03 11:32:14
All ModelBuilder functionality may not be exported. Edits may be required for equivalency with the original model.
"""

import arcpy
import json

# To allow overwriting the outputs change the overwrite option to true.
arcpy.env.overwriteOutput = False

# Script parameters
arcpy.env.workspace = arcpy.GetParameterAsText(0)

#Make sure to drop the config file in your ArcPro project
with open(arcpy.env.workspace+'/config.json') as json_data_file:
    data = json.load(json_data_file)

# Local variables:
roads = data["wfs_paths"]["WFS_roads_path"]
roads_buffer = data["temp_paths"]["roads_buffer"]
roads_buffer_path = r"" + arcpy.env.workspace + "\\roads_buffer"

# Process: Buffer
arcpy.Delete_management(roads_buffer)
arcpy.Buffer_analysis(in_features=roads, out_feature_class=roads_buffer, buffer_distance_or_field="100 Feet", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field="", method="PLANAR")


aprx = arcpy.mp.ArcGISProject("CURRENT")
map = aprx.listMaps()[0]  # assumes data to be added to first map listed
map.addDataFromPath(roads_buffer_path)
