# -*- coding: utf-8 -*-
"""Generated by ArcGIS ModelBuilder on: 2019-12-03 15:06:40
All ModelBuilder functionality may not be exported. Edits may be required for equivalency with the original model.
"""

import arcpy
import json

# To allow overwriting the outputs change the overwrite option to true.
arcpy.env.overwriteOutput = False

# Script parameters
arcpy.env.workspace = arcpy.GetParameterAsText(0)

#Make sure to drop the config file in your ArcPro project
with open(arcpy.env.workspace+'/config.json') as json_data_file:
    data = json.load(json_data_file)

# Local variables:
project_locations = "project_locations"
project_listings = "project_listings"
temp_project_listings_layer = "temp_project_listings_layer"
roads_buffer_clip2 = data["temp_paths"]["roads_buffer_clip2"]
project_locations_CopyFeatures1 = "project_locations_CopyFeatures1"
field = "L0project_locations_CCID"
cursor = arcpy.SearchCursor(project_locations_CopyFeatures1)


# Process: Calculate Field

arcpy.SelectLayerByLocation_management(project_locations, "ARE IDENTICAL TO", roads_buffer_clip2)


for row in cursor:
    #arcpy.AddMessage(row.getValue(field))
    CCID = row.getValue(field)
    CCIDstr = str(CCID)
    arcpy.AddMessage("CCID being passed into project_locations is "+CCIDstr)

    project_locations_feature_count = int(arcpy.GetCount_management(project_locations).getOutput(0))
    arcpy.AddMessage("Perform count of project_locations. This ensures there is only 1 selection of project_listings.")
    if project_locations_feature_count == 1:
        feature_count_str = str(project_locations_feature_count)
        arcpy.AddMessage(feature_count_str+" row was selected in the project_locations layer!")
        result = arcpy.CalculateField_management(in_table=project_locations, field="CCID", expression=CCID, expression_type="PYTHON3", code_block="")
        arcpy.AddMessage('{} has {} records'.format(project_locations, result[0]))
    else:
        feature_count_str = str(project_locations_feature_count)
        arcpy.AddMessage(feature_count_str + " row was selected in the project_locations layer!")
        arcpy.AddError("Please reselect your project. {1} rows were selected. Either 0 rows were selected or more than 1 row was selected from the project_locations layer.".format(project_locations, project_locations_feature_count))




